language: python
python:
  - "2.6"
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper autotools-dev cups-ppdc libcups2-dev cups
 - pip install httplib2 pycups pytest-cov --use-mirrors
install:
 - ./configure
 - sudo make install
script:
 - cd /usr/local/lib/cloudprint-cups/
 - py.test --cov .